### ISSUE TITLE
[FEATURE] 백엔드 GET Method 구현 

### ISSUE THREAD

**Issue by jstella96** [woowa-techcamp-2022/web-moneybook-03#16]
## 💼 TASK 개요 
* front-end 작업전 각 테이블의 get 요청 

## ✅ TODO 및 진행현황

- [x] account-history get API 구현 
- [x] category get API 구현
- [x] payment-method get API 구현 

## ⏰ 예상 소요 시간 
1h

**Comment by jstella96** [comment]
#42 번 이슈에서 구현했습니다:)
