### ISSUE TITLE
[FEATURE] account history 컴포넌트 구현 

### ISSUE THREAD

**Issue by jstella96** [woowa-techcamp-2022/web-moneybook-03#26]
## 💼 TASK 개요 
account history 컴포넌트 구현

## ✅ TODO 및 진행현황

- [ ] account history 클래스 기본 구조  잡기
- [ ] 디자인
- [ ] backend에게 데이터 요청
- [ ] 받아온 내역에 대해서 입출 지출 내역 계산
- [ ] row 클릭시 상단 input바에 필드값이 채워지도록 연계

## ⏰ 예상 소요 시간 
6h
