### ISSUE TITLE
[FEATURE] Create, Update, Delete API 구현 

### ISSUE THREAD

**Issue by jstella96** [woowa-techcamp-2022/web-moneybook-03#48]
## 💼 TASK 개요 
* GET API 를 제외한 나머지 API 개발
## ✅ TODO 및 진행현황

- [x] (PATCH) /acocunt-history/{id}

- [x] (POST) /account-history
- [x] (POST) /payment-method
- [x] (DELETE) /payment-method/{id}

- [x] (PATCH) /category/{id}

- [ ] (GET) /statistics?year=&month=
🙄get이 하나 남았군요
## ⏰ 예상 소요 시간 
2.5h
