### ISSUE TITLE
[FEATURE]  유저 인증 middleware에 추가

### ISSUE THREAD

**Issue by jstella96** [woowa-techcamp-2022/web-moneybook-03#50]
## 💼 TASK 개요 
* db 에 없는 userId 가 요청시 권한없음 에러를 반환하도록 middleware 추가

## ✅ TODO 및 진행현황

- [ ] 유저 인증 함수 개발( db 존재여부)
- [ ] backend에 middleware 추가 
- [ ] front-end 에서 요청시마다 X-USER-ID 를 header에 담아오도록 코드 수정
- [ ] backend에 하드코딩한 임시 id('star')제거

## ⏰ 예상 소요 시간 
1H
