### ISSUE TITLE
[FEATURE] AccountForm Validation 및 디자인 구체화

### ISSUE THREAD

**Issue by KimKwon** [woowa-techcamp-2022/web-moneybook-03#55]
## 🌴 작업 브랜치 

`feature/#55`

## 💼 TASK 개요 

AccountForm에서 올바른 값이 들어올 수 있도록 validation해요.
날짜 입력 등 input 태그 스타일링 및 css를 구체화 작업을 해요.

## ✅ TODO 및 진행현황 

- [x] 날짜 입력 정규식을 통해 `YYYYMMDD` 로 나타낼 수 있도록 하기
  - [x] 연관된 값 불러오는 로직 수정
- [x] AccountForm 전반적인 스타일링 구체화

## ⏰ 예상 소요 시간 

2h
