### ISSUE TITLE
[FEATURE] 통계페이지 하단 테이블 표출 

### ISSUE THREAD

**Issue by jstella96** [woowa-techcamp-2022/web-moneybook-03#61]
## 💼 TASK 개요 
* 통계페이지 하단에 테이블 표출 
* 이전에 사용했던 컴포넌트 재사용
## ✅ TODO 및 진행현황 
- [ ] 통계페이지 상단에 카테고리 버튼 임시 표출
- [ ] 통계페이지 하단에 테이블 표출
- [ ] 버튼 클릭시 날짜 바뀌는 이벤트 연결

## ⏰ 예상 소요 시간 
2h
