### ISSUE TITLE
[BUG] 버그 내역

### ISSUE THREAD

**Issue by jstella96** [woowa-techcamp-2022/web-moneybook-03#70]
## 💼 TASK 개요 
배포 전 버그 점검하겠습니다.

## ✅ TODO 및 진행현황 

- [x] 달을 넘길 때 달력페이지가 아닌 곳에서 달력 컴포넌트가  랜더링 되는 경우가 있음 - > 구독 문제로 추정 
- [x] 날짜에서 엔터를 누르면 전체내역이 업데이트 -> 엔터눌러도 submit이벤트가 발생됩니다 !! 
- [x] 꺾은선 그래프 버튼 작동안함 => 작동함 빈값표출 업데이트 속히 필요
- [x] 빈 데이터 일때 달력에 날짜가 1로 표출
- [x] 빈그래프 값이 비어있알때도 데이터 표출 -> 월 수 변했는데 안닫아짐
- [x] 달력 해당 월의 일수보다 많이 표출 
## ⏰ 예상 소요 시간 
<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
